language: rust
cache: cargo
sudo: false
os:
- linux
- osx
rust:
- nightly
- beta
- stable
script:
- cargo test
branches:
  only:
    master
after_success: |
  [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  [ "$TRAVIS_RUST_VERSION" == "stable" ] &&
  [ "$TRAVIS_OS_NAME" == "linux" ] &&
  bash ./publish-docs.sh
matrix:
  allow_failures:
    - rust: nightly
