[package]
name = "tokio-c-ares"
license = "MIT"
version = "0.1.0"
authors = ["David Hotham"]
description = """
An asynchronous DNS client using futures, backed by c-ares.
"""
homepage = "https://github.com/dimbleby/tokio-c-ares"
repository = "https://github.com/dimbleby/tokio-c-ares"
documentation = "https://dimbleby.github.io/tokio-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares", "futures", "tokio"]

[dependencies]
c-ares = "0.20.0"
futures = "0.1.2"
mio = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
ws2_32-sys = "0.2.1"

[dev-dependencies]
tokio-core = "0.1"


