[package]
name = "c-ares-resolver"
license = "MIT"
version = "0.1.0"
authors = ["David Hotham"]
description = """
An asynchronous DNS client using futures, backed by c-ares.
"""
homepage = "https://github.com/dimbleby/c-ares-resolver"
repository = "https://github.com/dimbleby/c-ares-resolver"
documentation = "https://dimbleby.github.io/c-ares-resolver"
readme = "README.md"
keywords = ["DNS", "c-ares", "futures"]

[dependencies]
c-ares = "0.20.0"
futures = "0.1.2"
mio = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
ws2_32-sys = "0.2.1"

[dev-dependencies]
dns-parser = "0.5.1"
tokio-core = "0.1"


